# Generated by Django 4.1.1 on 2022-09-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image_uploads', models.ImageField(blank=True, upload_to='images/')),
                ('image_link', models.URLField(blank=True, default='String', max_length=255)),
                ('video_uploads', models.FileField(blank=True, upload_to='videos/')),
                ('video_link', models.URLField(blank=True, default='String', max_length=255)),
            ],
        ),
    ]
