# Generated by Django 4.1.1 on 2022-09-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacked', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_uploads',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='video_uploads',
        ),
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.URLField(default='String', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.URLField(default='String', max_length=255),
        ),
    ]
