# Generated by Django 4.1.1 on 2022-09-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacked', '0002_rename_image_post_image_uploads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True, default='String', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_uploads',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_link',
            field=models.URLField(blank=True, default='String', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_uploads',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
