# Generated by Django 4.1.1 on 2022-09-14 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('image_uploads', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_link', models.URLField(blank=True, default='String', max_length=500, null=True)),
                ('video_uploads', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_link', models.URLField(blank=True, default='String', max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
