# Generated by Django 4.1.1 on 2022-09-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0002_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True, default='', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_link',
            field=models.URLField(blank=True, default='', max_length=700, null=True),
        ),
    ]
