# Generated by Django 4.1.1 on 2022-09-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0003_alter_post_image_link_alter_post_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='username',
        ),
    ]
