# Generated by Django 4.1.1 on 2022-09-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0004_rename_user_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
