# Generated by Django 4.1.1 on 2022-09-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0006_alter_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_link',
        ),
    ]
